name: Tests
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: minikube start
    - run: kubectl apply -k config/default
    - run: python -m pip install -r test-requirements.txt
    - run: python -m pytest tests