name: Python package
on: [push]
jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox:
        - python-version: 3.7
          toxenv: py37
        - python-version: 3.8
          toxenv: py38
        - python-version: 3.9
          toxenv: py39
        - python-version: 3.9
          toxenv: style
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -r test-requirements.txt
      - name: Test with pytest
        run: pytest src
        env:
          PYTHONPATH: ${{ github.workspace }}
      - name: Check upgrade dependencies
        run: |
          python -m pip install pip-tools
          python -m pip install -r <(pip-compile requirements.in 2>&1)
      - name: Test upgraded with pytest
        run: pytest src
        env:
          PYTHONPATH: ${{ github.workspace }}
