name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Test with pytest
        run: pytest src
      - name: Check upgrade dependencies
        run: python -m pip install -r =(pip-compile requirements.in 2>&1)
      - name: Test upgraded with pytest
        run: pytest src